spring.application.name=zorrobpm-handler-examle

spring.rabbitmq.addresses=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:zorrodev}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:zorrodev}
